title: The best 1º Blog [that I've ever written]
author: Diogo Jorge Basso
email: diogo@ensinu.com.br
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Esse é um blog voltado para qualquer ávido em programação e
  na benfazeja mudança que isso causará!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  DiogoJBasso # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
